main: me.jackjack33.jackscars.Main
version: 1.0
name: JacksCars
authors: [JackJack33, Santio71, AppleFlavored]
description: A good cars plugin
api-version: 1.13

commands:
  jackscars:
    description: Main command used for JacksCars.
    aliases: ["jc", "cars"]
